config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'students#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :student
  validates :description, presence: true, length: {minimum: 10, maximum: 100}
  validates :title, presence: true, length: {minimum: 10, maximum: 100}
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true,
                   uniqueness: {case_sensitive: false},
                   length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 105},
                    format: {with: VALID_EMAIL_REGEX}
  has_many :lists
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @list= List.all.order(id: :desc)
    
  end

  def show

  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params.require(:list).permit(:student_id, :title, :description))
    @list.student = Student.first
    if @list.save
      flash[:notice]="successfully saved"
      redirect_to lists_path(@list)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @list.update(list_params)
      flash[:notice]="successfully"
      redirect_to list_path(@list)
    else
      render 'edit'
    end
  end

  def destroy

    @list.destroy
    redirect_to lists_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:Student, :title, :description, :student_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end 
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @list= @student.lists
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  def update
      @student = Student.find(params[:id])
      if @student.update(student_params)
          flash[:notice] = "Student #{@student.name} was successfully updated!"
          redirect_to lists_path
      else
          render 'edit'
      end
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
      if @student.save
        flash[:notice]="Student #{@student.name} created!"
        redirect_to lists_path(@list)
      else
        render 'new'
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
      @student = Student.find(params[:id])
      if @student.update(student_params)
          flash[:notice] = "Student #{@student.name} was successfully updated!"
          redirect_to lists_path
      else
          render 'edit'
      end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :email, :password)

    end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(student, options ={size: 80})
    email_address = student.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url= "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: student.name, class:"rounded shadow mx-auto d-block")
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%=link_to 'Tram Lai', 'http://tramlai.com/', class: 'text-white'%></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= msg%>
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
<% end %>
</div>
</div>

app/views/layouts/_navigationbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to 'Practice App', root_path, class:'navbar-brand', id: 'logo' %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to 'List of students', students_path, class: 'nav-link' %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Lists
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'Create new list', new_list_path, class: 'dropdown-item' %>
        <%= link_to 'View lists', lists_path, class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </li>
  </ul>
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column">
    <header>
      <%= render 'layouts/navigationbar'%>
    </header>
    <div id="page-content">
      <div class="container">
        <%= render 'layouts/messages'%>
        <%= yield %>
      </div>
    </div>
     <%= render 'layouts/footer'%>

  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">
<%= render "shared/errormessages", obj: @list%>
  <div class="row justify-content-center">
    <div class="col-10">
    <%= form_with(model: @list,class:"shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
     <div class="form-group row">
    <%= f.label :title, class: "col-sm-2 col-form-label text-light"%>
    <div class="col-sm-10">
    <%= f.text_field :title, class: "form-control shadow rounded", placeholder: 'Title'%>
      </div>
      </div>
      <div class="form-group row">
    <%= f.label :description, class: "col-sm-2 col-form-label text-light"%>
    <div class="col-sm-10">
    <%= f.text_area :description, rows: 5, class: "form-control shadow rounded", placeholder: 'Description'%>
      </div>
      </div>
    <div class="form-group row justify-content-md-center">
      <%= f.submit class: "btn btn-outline-light btn-lg"%>
    </div>
    <% end %>
    <div class="form-group row justify-content-md-center">
      <%= link_to '[Return to the list]', lists_path, class: 'text-info'%>
    </div>
  </div>
  </div>
</div>

app/views/lists/_lists.html.erb
<h1 class="text-center mt-4">Showing the list</h1>
<% @list.each do |f| %>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
  <div class="card text-center shadow p-3 mb-5 bg-white rounded">
    <div class="card-header font-italic">
      By <%= f.student.name if f.student %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to f.title, list_path(f), class: 'text-success'%></h5>
      <p class="card-text"><%= truncate(f.description, length: 100) %></p>
      <%= link_to 'View', list_path(f), class: 'btn btn-info'%>
      <%= link_to 'Edit', edit_list_path(f), class: 'btn btn-success'%>
      <%= link_to 'Delete', list_path(f), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'%>
    </div>
    <div class="card-footer text-muted">
      Created <%= time_ago_in_words(f.created_at) %> ago, updated <%= time_ago_in_words(f.updated_at) %> ago
    </div>
  </div>
</div>
</div>
</div>
<%end%>

app/views/lists/edit.html.erb
  <h1 class="text-center mt-4">Editing List</h1>
<%= render 'form'%>

app/views/lists/index.html.erb
<%= render 'lists'%>

app/views/lists/new.html.erb
<h1 class="text-center mt-4">New List</h1>
<%= render 'form'%>

app/views/lists/show.html.erb
  <h2 class="text-center mt-4"><%= @list.title%></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
    <div class="card text-center shadow p-3 mb-5 bg-white rounded">
      <div class="card-header font-italic">
        By <%= @list.student.name if @list.student%>
      </div>
      <div class="card-body">
        <p class="card-text text-left"><%= simple_format(@list.description)%></p>
        <%= link_to 'Edit', edit_list_path(@list), class: 'btn btn-success'%>
        <%= link_to 'Delete', list_path(@list), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'%>
      </div>
      <div class="card-footer text-muted">
        Created <%= time_ago_in_words(@list.created_at) %> ago, updated <%= time_ago_in_words(@list.updated_at) %> ago
      </div>
    </div>
  </div>
  </div>
  </div>

app/views/pages/about.html.erb
<h1>this is about page</h1>

app/views/pages/home.html.erb
<div class="container" id="home-container">
<div class="jumbotron text-center text-white">
  <h1 class="display-4">Practice App</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg"%>
</div>
</div>

app/views/shared/_errormessages.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following prevented <%= obj.class.name.downcase %> from being saved!</h4>
  <% obj.errors.full_messages.each do |msg| %>
  <ul>
    <li><%= msg%></li>
  </ul>
  <% end %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/students/_form.html.erb
<div class="container">
<%= render "shared/errormessages", obj: @student%>
  <div class="row justify-content-center">
    <div class="col-10">
    <%= form_with(model: @student, class: "shadow p-3 mb-3 bg-info rounded", local:true) do |f| %>
    <div class="form-group row">
      <%= f.label :name, class: "col-sm-2 col-form-label text-light"%>
      <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter student name" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :password, class: "col-sm-2 col-form-label text-light" %>
      <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter password" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :email, class: "col-sm-2 col-form-label text-light" %>
      <div class="col-sm-10">
      <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter email" %>
      </div>
    </div>
    <div class="form-group row justify-content-md-center">
      <%= f.submit(@student.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
    </div>

    <% end %>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<h1 class="text-center mt-4">Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1 class="text-center mt-4">list of students</h1>
<% @students.each do |f| %>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
  <div class="card text-center shadow p-3 mb-5 bg-white rounded">
    <div class="card-header font-italic">
      By <%= link_to f.name, f %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to gravatar_for(f, size: 200), f %></h5>
      <p class="card-text"><%= pluralize(f.lists.count, "list", plural: "lists") %></p>
      <%= link_to 'View profile', f, class: 'btn btn-info'%>
      <%= link_to 'Edit profile', edit_student_path(f), class: 'btn btn-success'%>

    </div>
    <div class="card-footer text-muted">
      Joined <%= time_ago_in_words(f.created_at) %> ago
    </div>
  </div>
</div>
</div>
</div>
<%end%>

app/views/students/new.html.erb
<h1 class="text-center mt-4">New Student</h1>

<%= render 'form'%>

app/views/students/show.html.erb
  <h2 class="text-center mt-4"><%= @student.name%> profile</h2>
  <%= gravatar_for @student, size: 200 %>
  <h3 class="text-center mt-4">Articles</h3>
  <%= render "lists/lists"%>